### ISSUE TITLE
Private transparent proxy cache url downloaded  the file really slow 

### ISSUE THREAD

**Issue by polupraneeth** [Kevinrob/guzzle-cache-middleware#68] opened 2016-09-16 19:17 UTC
# Trying to download Private transparent proxy cache url with guzzle

I am trying to download a file from a file sharing website, but it really slows down the execution of the script. For large files it is giving me a time out error. I tried everything, but I'm still unable to download the cache URL files, as fast as it can be.
`use GuzzleHttp\Client;
    use GuzzleHttp\HandlerStack;

```
use Kevinrob\GuzzleCache\CacheMiddleware;
use Doctrine\Common\Cache\ChainCache;
use Doctrine\Common\Cache\ArrayCache;
use Doctrine\Common\Cache\FilesystemCache;
use Kevinrob\GuzzleCache\Strategy\PrivateCacheStrategy;
use Kevinrob\GuzzleCache\Storage\DoctrineCacheStorage;

use GuzzleHttp\Psr7;
use GuzzleHttp\Cookie\FileCookieJar;

$current_dir = getcwd();
$temp_dir = "/temp/"; 
$cache_dir = "/cache/";

$stack = HandlerStack::create();
$stack->push(new CacheMiddleware(
new PrivateCacheStrategy(
new DoctrineCacheStorage(
new ChainCache([
new ArrayCache(),
new FilesystemCache($current_dir . $cache_dir),
])
)
)
), 'cache');


// Guzzle init
$cookieJar = new FileCookieJar($current_dir . $temp_dir .'jar.txt', true);
$client = new Client([
'defaults' => ['debug' => true],
'verify' => $current_dir . $temp_dir ."cacert.pem",
'handler' => $stack,
'cookies' => $cookieJar
]);

$download_file = "http://affix.is/mp3embed-1cg17i8ptsc8.mp3";
$resource = fopen($current_dir . $temp_dir ."temp.ext", 'w');
$response = $client->request('GET', $download_file, ['sink' => $resource]);
echo html_status($response);`
```

**Comment by Kevinrob** [comment] 2017-02-04 09:34
Hi @polupraneeth, I don't realy understand what is your issue 😄. I'm not realy sure that this is related to this library.
I close this issue for the moment, if you need more help about that, don't hesitate to respond 😉.

**Closed by Kevinrob** 2017-02-04 09:34 UTC

**Comment by josenobile** [comment] 2017-03-26 17:08
Hello, 

I think the problem is guzzle cache middleware does not support sink parameter. Does it support?

**Comment by Kevinrob** [comment] 2017-03-27 07:32
Hi, how should it support sink parameter? Don't do caching?
